# documentation: https://github.com/TriliumNext/Notes
# slogan: Build your personal knowledge base with TriliumNext Notes.
# tags: self-hosted, notes, todo, organize, markdown, wiki
# logo: svgs/triliumnext.svg
# port: 8080

services:
  triliumnext:
    image: triliumnext/notes:latest
    environment:
      - SERVICE_FQDN_TRILIUMNEXT_8080
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - triliumnext_data:/home/node/trilium-data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://127.0.0.1:8080/api/health-check || exit 1",
        ]
      interval: 5s
      timeout: 20s
      retries: 10
